import Head from "next/head";
import { useState } from "react";
import type { NextPage } from "next";
import styles from "../styles/Home.module.scss";
import List from "../components/List";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { findSiteData, findNavData, FindSiteQuery } from "../globals/apis";
import { SiteListContext } from "./hooks/SiteListContext";
import { NavigationListContext } from "./hooks/NavigationListContext";
import type { SiteListResponse } from "../types/site";
import type { NavigationListResponse } from "../types/navigation";

const queryDetail: FindSiteQuery = {
  size: 20,
  page: 1,
  type: undefined,
};

export async function getStaticProps() {
  const navigation = await findNavData();
  const site = await findSiteData();
  //   console.log("site=================", site);
  //   console.log("navigation=================", navigation);
  return {
    props: {
      site,
      navigation,
    },
  };
}

type HomeProps = {
  site: SiteListResponse;
  navigation: NavigationListResponse;
};

const Home: NextPage<HomeProps> = ({ site, navigation }: HomeProps) => {
  const [navList] = useState(navigation.list);
  const [list, setList] = useState(site.list);
  const [query, setQuery] = useState(queryDetail);
  const [total, setTotal] = useState(site.total);
  //   const siteContext = { list, setList, query, setQuery, total, setTotal }
  return (
    <div className={styles.container}>
      <Head>
        <title>vue.design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationListContext.Provider value={{ navList }}>
        <Header />
      </NavigationListContext.Provider>
      <SiteListContext.Provider
        value={{ list, setList, query, setQuery, total, setTotal }}
      >
        <List type="home" />
        <Footer />
      </SiteListContext.Provider>
    </div>
  );
};

export default Home;
