import Head from "next/head";
import type { NextPage } from "next";
import styles from "./styles/Home.module.scss";
import List from "./components/List";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { SiteContext } from "./hooks/SiteContext";
import { NavigationContext } from "./hooks/NavigationContext";
import { initializeApollo, addApolloState } from "./libs/apolloClient";
import { INDEX_QUERY } from "./libs/gql";
import { useQuery } from "@apollo/client";

export async function getStaticProps() {
  const apolloClient = initializeApollo();
  await apolloClient.query({
    query: INDEX_QUERY,
    variables: {},
  });
  return addApolloState(apolloClient, {
    props: {},
    revalidate: 1,
  });
}

type HomeProps = {};

const Home: NextPage<HomeProps> = ({}: HomeProps) => {
  const { loading, error, data, fetchMore, networkStatus } = useQuery(
    INDEX_QUERY,
    {
      variables: {},
    }
  );
  console.log("error==========", error);
  console.log("data", data);
  return (
    <div className={styles.container}>
      <Head>
        <title>vue.design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationContext.Provider
        value={{ ...data.navigations, profile: data.profile }}
      >
        <Header />
      </NavigationContext.Provider>
      <SiteContext.Provider value={data.sites}>
        <List type="home" />
        <Footer />
      </SiteContext.Provider>
    </div>
  );
};

export default Home;
