// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    IconDown: typeof import('./src/components/IconDown.vue')['default']
    IconGithub: typeof import('./src/components/IconGithub.vue')['default']
    IconHome: typeof import('./src/components/IconHome.vue')['default']
    IconLike: typeof import('./src/components/IconLike.vue')['default']
    IconRecommend: typeof import('./src/components/IconRecommend.vue')['default']
    IconSetting: typeof import('./src/components/IconSetting.vue')['default']
    IconUp: typeof import('./src/components/IconUp.vue')['default']
    VueDesignItem: typeof import('./src/components/VueDesignItem.vue')['default']
  }
}

export { }
