import type { NextPage } from 'next';
import Head from 'next/head';
import List from '@/modules/components/List';
import Top from '@/modules/components/Top';
import Footer from '@/modules/components/Footer';
import UserHeader from '@/modules/components/UserHeader';
import { wrapper } from '@/modules/store';
import { sites } from '@/modules/services/siteApi';
import { user } from '@/modules/services/userApi';
import { count } from '@/modules/services/countApi';
import { User } from '@/modules/types/auth';
import { getUuid } from '@/modules/utils';
import styles from './User.module.scss';

type UserProps = {
    user: User;
    uuid: string;
};

export const getServerSideProps = wrapper.getServerSideProps(
    (store) => async (context) => {
        const uuid = getUuid(context.params!.uuid);
        const { data: userData } = await store.dispatch(user.initiate(uuid));
        if (!userData) {
            return {
                props: {} as UserProps,
            };
        }
        await store.dispatch(
            sites.initiate({
                page: 1,
                size: 20,
                authorId: userData.id,
            }),
        );
        await store.dispatch(count.initiate(userData.id));
        return {
            props: {
                user: userData,
                uuid,
            },
        };
    },
);

const User: NextPage<UserProps> = ({ user, uuid }: UserProps) => {
    return (
        user &&
        uuid && (
            <div className={styles.container}>
                <Head>
                    <title>vue.design-profile</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className={styles['top-bg']}>
                    <Top />
                </div>
                <UserHeader user={user} />
                <List type="user" authorId={user.id} uuid={uuid} />
                <Footer />
            </div>
        )
    );
};

export default User;
