import type { NextPage } from 'next';
import Head from 'next/head';
import List from '@/modules/components/List';
import Top from '@/modules/components/Top';
import Footer from '@/modules/components/Footer';
import UserHeader from './components/UserHeader';
import styles from './User.module.scss';
import { wrapper } from '@/modules/redux/store';
import { sites } from '@/modules/redux/services/siteApi';
import { user } from '@/modules/redux/services/userApi';
import { count } from '@/modules/redux/services/countApi';
import { User } from '@/modules/redux/types/auth';
import { getUuid } from '@/globals/utils';

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
    const uuid = getUuid(context.params!.uuid);
    const { data: userData } = await store.dispatch(user.initiate(uuid));
    await store.dispatch(
      sites.initiate({
        page: 1,
        size: 20,
        authorId: userData.id,
      }),
    );
    await store.dispatch(count.initiate(userData.id));
    return {
      props: {
        user: userData,
      },
    };
  },
);

type UserProps = {
  user: User;
};

const User: NextPage<UserProps> = ({ user }: UserProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>vue.design-profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles['top-bg']}>
      <Top />
      </div>
      <UserHeader user={user} />
      <List type="user" authorId={user.id} />
      <Footer />
    </div>
  );
};

export default User;
