import type { NextPage } from 'next';
import Head from 'next/head';
import List from '@/modules/components/List';
import Top from '@/modules/components/Top';
import Footer from '@/modules/components/Footer';
import Nav from '@/modules/components/Nav';
import { wrapper } from '@/modules/store';
import { sites } from '@/modules/services/siteApi';
import styles from './Sites.module.scss';

export const getServerSideProps = wrapper.getServerSideProps(
    (store) => async (context) => {
        await store.dispatch(
            sites.initiate({
                page: 1,
                size: 20,
            }),
        );
        return {
            props: {},
        };
    },
);

type SitesProps = {};

const Sites: NextPage<SitesProps> = ({}: SitesProps) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>vue.design-find</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <Top />
            </header>
            <section className={styles.main}>
                <Nav />
            </section>
            <List type="find" />
            <Footer />
        </div>
    );
};

export default Sites;
