import type { NextPage } from 'next';
import Head from 'next/head';
import List from '@/modules/components/List';
import Top from '@/modules/components/Top';
import Footer from '@/modules/components/Footer';
import Nav from './components/Nav';
import styles from './Site.module.scss';

export async function getServerSideProps() {
  return {
    props: {},
  };
}

type SiteProps = {};

const Site: NextPage<SiteProps> = ({}: SiteProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>vue.design-find</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Top />
      </header>
      <section className={styles.main}>
        <Nav />
      </section>
      <List type="find" />
      <Footer />
    </div>
  );
};

export default Site;
