import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Find.module.scss'
import List from '../components/List'
import Top from '../components/Top'
import Nav from '../components/Nav'
import Footer from '../components/Footer'

const Find: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>vue.design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Top />
      </header>
      <section className={styles.main}>
        <Nav />
      </section>
      <List />
      <Footer />
    </div>
  )
}

export default Find
