import Head from 'next/head'
import { useState } from 'react'
import type { NextPage } from 'next'
import styles from '../styles/Home.module.scss'
import List from '../components/List'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { findSite, FindSiteQuery } from '../globals/apis'
import { SiteListContext } from './hooks/SiteListContext'
import type { SiteListResponse } from '../types/site'

const queryDetail: FindSiteQuery = {
  size: 20,
  page: 1,
  type: 'all'
}

export async function getStaticProps() {
  const site = await findSite()
  return {
    props: {
      site
    }
  }
}

type HomeProps = {
  site: SiteListResponse
}

const Home: NextPage<HomeProps> = ({ site }: HomeProps) => {
  const [list, setList] = useState(site.list)
  const [query, setQuery] = useState(queryDetail)
  const [total, setTotal] = useState(site.total)
  const context = { list, setList, query, setQuery, total, setTotal }
  return (
    <div className={styles.container}>
      <SiteListContext.Provider value={context}>
        <Head>
          <title>vue.design</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <List type="home" />
        <Footer />
      </SiteListContext.Provider>
    </div>
  )
}

export default Home
