import Head from 'next/head';
import Link from 'next/link';
import type { NextPage } from 'next';
import { wrapper } from '@/modules/store';
import { sites } from '@/modules/services/siteApi';
import { navigations } from '@/modules/services/navigationApi';
import Header from '@/modules/components/Header';
import List from '@/modules/components/List';
import Buttom from '@/modules/components/Bottom';
import Footer from '@/modules/components/Footer';
import styles from './Home.module.scss';

export const getServerSideProps = wrapper.getServerSideProps(
    (store) => async (context) => {
        await store.dispatch(navigations.initiate());
        await store.dispatch(
            sites.initiate({
                page: 1,
                size: 20,
            }),
        );
        return {
            props: {},
        };
    },
);

type HomeProps = {};

const Home: NextPage<HomeProps> = ({}: HomeProps) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>vue.design</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <List pageType="home" />
            <Buttom />
            <Footer />
        </div>
    );
};

export default Home;
