import Head from 'next/head';
import type { NextPage } from 'next';
import { wrapper } from '@/modules/store';
import { sites } from '@/modules/services/siteApi';
import { navigations } from '@/modules/services/navigationApi';
import { setQuery } from '@/modules/features/siteSlice';
import Header from '@/modules/components/Header';
import List from '@/modules/components/List';
import Buttom from '@/modules/components/Bottom';
import Footer from '@/modules/components/Footer';
import styles from './Home.module.scss';

export const getServerSideProps = wrapper.getServerSideProps(
    (store) => async () => {
        const params = {
            page: 1,
            size: 20,
        };
        await store.dispatch(navigations.initiate());
        await store.dispatch(sites.initiate(params));
        await store.dispatch(setQuery(params));
        return {
            props: {
                params,
            },
        };
    },
);

type HomeProps = {
    params: {
        page: number;
        size: number;
    };
};

const Home: NextPage<HomeProps> = ({ params }: HomeProps) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>vue.design</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <List pageType="home" params={params} />
            <Buttom />
            <Footer />
        </div>
    );
};

export default Home;
