import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Info, PersonalPrivacy, Connect, Help } from '@icon-park/react';
import { wrapper } from '@/modules/store';
import Top from '@/modules/components/Top';
import Footer from '@/modules/components/Footer';
import { getParamsByContext } from '@/modules/utils';
import styles from './Page.module.scss';
import { configure, useConfigureQuery } from '@/modules/services/configureApi';
import { Viewer } from '@bytemd/react';
import markdownStyles from './markdown.module.scss';
import frontmatter from '@bytemd/plugin-frontmatter';
import gemoji from '@bytemd/plugin-gemoji';
import gfm from '@bytemd/plugin-gfm';
import highlightSsr from '@bytemd/plugin-highlight-ssr';
import mathSsr from '@bytemd/plugin-math-ssr';
import mermaid from '@bytemd/plugin-mermaid';

// 编辑插件
const plugins = [
    frontmatter(),
    gemoji(),
    gfm(),
    highlightSsr(),
    mathSsr(),
    mermaid(),
];

const leftNav = [
    {
        path: 'about',
        name: '关于我们',
        component: <Info theme="filled" size="14" />,
    },
    {
        path: 'privacy',
        name: '隐私政策',
        component: <PersonalPrivacy theme="filled" size="14" />,
    },
    {
        path: 'help',
        name: '使用文档',
        component: <Help theme="filled" size="14" />,
    },
    {
        path: 'link',
        name: '友情链接',
        component: <Connect theme="filled" size="14" />,
    },
];

type PageProps = {
    pageName: string;
};

export const getServerSideProps = wrapper.getServerSideProps(
    (store) => async (context) => {
        console.log('context', context.params);
        const pageName = getParamsByContext<typeof context>(
            context,
            'pageName',
        );
        console.log('context pageName', pageName);
        await store.dispatch(configure.initiate(pageName));
        return {
            props: {
                pageName,
            },
        };
    },
);

const Page: NextPage<PageProps> = ({ pageName }) => {
    const { data: detail } = useConfigureQuery(pageName);
    return (
        <div className={styles.container}>
            <Head>
                <title>vue.design-site</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link rel="icon" href={'/styles/highlight-github.css'} />
            </Head>
            <header className={styles.header}>
                <Top />
            </header>
            <section className={styles.main}>
                <aside className={styles['asider-left']}>
                    <ul>
                        {leftNav.map((item, key) => {
                            return (
                                <li
                                    key={key}
                                    className={
                                        item.path === pageName
                                            ? styles.active
                                            : undefined
                                    }>
                                    {item.component}
                                    <Link href={`/page/${item.path}`}>
                                        {item.name}
                                    </Link>
                                </li>
                            );
                        })}
                    </ul>
                </aside>
                <article className={styles.article}>
                    {detail && (
                        <>
                            <header className={styles.title}>
                                <h1>{detail.value}</h1>
                            </header>
                            <div className={styles.content}>
                                <div
                                    className={markdownStyles['markdown-body']}>
                                    {detail.content && (
                                        <Viewer
                                            value={detail.content}
                                            plugins={plugins}
                                        />
                                    )}
                                </div>
                            </div>
                        </>
                    )}
                </article>
                <aside className={styles['asider-right']}></aside>
            </section>
            <Footer />
        </div>
    );
};

export default Page;
