import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { GithubOne, Home, TagOne } from '@icon-park/react';
import { wrapper } from '@/modules/store';
import { count } from '@/modules/services/countApi';
import Top from '@/modules/components/Top';
import Footer from '@/modules/components/Footer';
import Tools from '@/modules/components/Tools';
import { getParamsByContext } from '@/modules/utils';
import Asider from '@/modules/components/Asider';
import styles from './Page.module.scss';
import { tool } from '@/modules/services/authApi';
import { typeMap } from '@/configs/globals.contants';

type PageProps = {
    pageName: string;
};

export const getServerSideProps = wrapper.getServerSideProps(
    (store) => async (context) => {
        const pageName = getParamsByContext<typeof context>(
            context,
            'pageName',
        );

        return {
            props: {
                pageName,
            },
        };
    },
);

const Page: NextPage<PageProps> = ({ pageName }) => {
    const detail = {
        title: 'vue.design隐私政策',
        updatedAt: 'xxx',
        description: 'xxx;ks;dfs;dfs;dkf;l;',
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>vue.design-site</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <Top />
            </header>
            <section className={styles.main}>
                <aside className={styles['asider-left']}>
                    <ul>
                        <li className={'active'}>
                            <a>关于我们</a>
                        </li>
                        <li>
                            <a>隐私政策</a>
                        </li>
                        <li>
                            <a>关于我们</a>
                        </li>
                    </ul>
                </aside>
                <article className={styles.article}>
                    <header className={styles.title}>
                        <h1>{detail.title}</h1>
                    </header>
                    <div className={styles.content}>
                        <div className="draft-container">
                            <p></p>
                            <p>
                                <strong>
                                    <span>
                                        <span>vue.design隐私政策</span>
                                    </span>
                                </strong>
                            </p>
                            <p></p>
                        </div>
                    </div>
                </article>
                <aside className={styles['asider-right']}></aside>
            </section>
            <Footer />
        </div>
    );
};

export default Page;
