import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from './Register.module.scss';
import RegisterPanel from '@/modules/components/RegisterPanel';
import { Divider } from 'antd';

const Register: NextPage<any> = () => {
    const router = useRouter();
    const finish = () => {
        router.push('/login');
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>vue.design</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.container}>
                <div className={styles.inner}>
                    <div className={styles.left}>
                        <div className={styles['left-inner']}>
                            <Divider orientation="left">注册</Divider>
                            <RegisterPanel finish={finish} />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Register;
