import type { NextPage } from 'next';
import Head from 'next/head';
import styles from './styles/Detail.module.scss';
import Top from './components/Top';
import Footer from './components/Footer';
import { wrapper } from './redux/store';
import { site } from './redux/services/client';
import { profile } from './redux/services/auth';
import { setToken, setUser } from './redux/features/authSlice';
import { setSiteItem } from './redux/features/clientSlice';
import Asider from './components/Asider';
import { SiteItem } from '../types/site';
import { User } from '../types/user';

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async ({ req, params }) => {
      const uuid = params?.uuid || '';
      await store.dispatch(setToken(req.cookies.token || ''));
      const { data: user } = await store.dispatch(profile.initiate());
      await store.dispatch(setUser(user as User));
      const { data: siteItem } = await store.dispatch(
        site.initiate(uuid as string),
      );
      await store.dispatch(setSiteItem(siteItem as SiteItem));
      return {
        props: {
          siteItem,
        },
      };
    },
);

type DetailProps = {
  siteItem: SiteItem;
};

const Detail: NextPage<DetailProps> = ({ siteItem }: DetailProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>vue.design-detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Top />
      </header>
      <section className={styles.main}>
        {siteItem && (
          <section className={styles.content}>
            <h1>{siteItem.title}</h1>
            <div>
              <span>[{siteItem.type}]</span>
              <span> · </span>
              <span>{siteItem.createdAt}</span>
              <span> · </span>
              <span>阅读 {siteItem.views}</span>
            </div>
            <div>{siteItem.description}</div>
          </section>
        )}
        <Asider />
      </section>
      <Footer />
    </div>
  );
};

export default Detail;
